System:
  DataDir: /home/username/data
  TempDir: /mnt/cwoj_tmp
  DatabaseHost: localhost
  DatabaseUser: YOUR_USERNAME
  DatabasePass: YOUR_PASSWORD
  DatabaseName: cwoj

Language1:
  FileExtension: cpp
  ExtraMemory: 20480
  CompilationExec: g++ -static -std=c++03 -fno-asm -s -Wall -O2 -lm -DONLINE_JUDGE -o target.exe

Language2:
  FileExtension: c
  ExtraMemory: 20480
  CompilationExec: gcc -static -std=c99 -fno-asm -s -Wall -O2 -lm -DONLINE_JUDGE -o target.exe

Language3:
  FileExtension: pas
  ExtraMemory: 20480
  CompilationExec: fpc -Xs -Sgic -O2 -dONLINE_JUDGE -otarget.exe

Language4:
  FileExtension: cpp
  ExtraMemory: 20480
  CompilationExec: g++ -static -std=c++11 -s -Wall -O2 -lm -DONLINE_JUDGE -o target.exe
