# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangyutong926/Workspace/cwoj_daemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangyutong926/Workspace/cwoj_daemon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangyutong926/Workspace/cwoj_daemon/CMakeFiles /home/zhangyutong926/Workspace/cwoj_daemon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangyutong926/Workspace/cwoj_daemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cwoj_daemon_runner

# Build rule for target.
cwoj_daemon_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cwoj_daemon_runner
.PHONY : cwoj_daemon_runner

# fast build rule for target.
cwoj_daemon_runner/fast:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/build
.PHONY : cwoj_daemon_runner/fast

#=============================================================================
# Target rules for targets named cwoj_daemon_daemon

# Build rule for target.
cwoj_daemon_daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cwoj_daemon_daemon
.PHONY : cwoj_daemon_daemon

# fast build rule for target.
cwoj_daemon_daemon/fast:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/build
.PHONY : cwoj_daemon_daemon/fast

src/daemon/call_ruc.o: src/daemon/call_ruc.cpp.o

.PHONY : src/daemon/call_ruc.o

# target to build an object file
src/daemon/call_ruc.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/call_ruc.cpp.o
.PHONY : src/daemon/call_ruc.cpp.o

src/daemon/call_ruc.i: src/daemon/call_ruc.cpp.i

.PHONY : src/daemon/call_ruc.i

# target to preprocess a source file
src/daemon/call_ruc.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/call_ruc.cpp.i
.PHONY : src/daemon/call_ruc.cpp.i

src/daemon/call_ruc.s: src/daemon/call_ruc.cpp.s

.PHONY : src/daemon/call_ruc.s

# target to generate assembly for a file
src/daemon/call_ruc.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/call_ruc.cpp.s
.PHONY : src/daemon/call_ruc.cpp.s

src/daemon/cena_validator.o: src/daemon/cena_validator.cpp.o

.PHONY : src/daemon/cena_validator.o

# target to build an object file
src/daemon/cena_validator.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/cena_validator.cpp.o
.PHONY : src/daemon/cena_validator.cpp.o

src/daemon/cena_validator.i: src/daemon/cena_validator.cpp.i

.PHONY : src/daemon/cena_validator.i

# target to preprocess a source file
src/daemon/cena_validator.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/cena_validator.cpp.i
.PHONY : src/daemon/cena_validator.cpp.i

src/daemon/cena_validator.s: src/daemon/cena_validator.cpp.s

.PHONY : src/daemon/cena_validator.s

# target to generate assembly for a file
src/daemon/cena_validator.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/cena_validator.cpp.s
.PHONY : src/daemon/cena_validator.cpp.s

src/daemon/database.o: src/daemon/database.cpp.o

.PHONY : src/daemon/database.o

# target to build an object file
src/daemon/database.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/database.cpp.o
.PHONY : src/daemon/database.cpp.o

src/daemon/database.i: src/daemon/database.cpp.i

.PHONY : src/daemon/database.i

# target to preprocess a source file
src/daemon/database.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/database.cpp.i
.PHONY : src/daemon/database.cpp.i

src/daemon/database.s: src/daemon/database.cpp.s

.PHONY : src/daemon/database.s

# target to generate assembly for a file
src/daemon/database.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/database.cpp.s
.PHONY : src/daemon/database.cpp.s

src/daemon/http.o: src/daemon/http.cpp.o

.PHONY : src/daemon/http.o

# target to build an object file
src/daemon/http.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/http.cpp.o
.PHONY : src/daemon/http.cpp.o

src/daemon/http.i: src/daemon/http.cpp.i

.PHONY : src/daemon/http.i

# target to preprocess a source file
src/daemon/http.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/http.cpp.i
.PHONY : src/daemon/http.cpp.i

src/daemon/http.s: src/daemon/http.cpp.s

.PHONY : src/daemon/http.s

# target to generate assembly for a file
src/daemon/http.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/http.cpp.s
.PHONY : src/daemon/http.cpp.s

src/daemon/json_builder.o: src/daemon/json_builder.cpp.o

.PHONY : src/daemon/json_builder.o

# target to build an object file
src/daemon/json_builder.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/json_builder.cpp.o
.PHONY : src/daemon/json_builder.cpp.o

src/daemon/json_builder.i: src/daemon/json_builder.cpp.i

.PHONY : src/daemon/json_builder.i

# target to preprocess a source file
src/daemon/json_builder.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/json_builder.cpp.i
.PHONY : src/daemon/json_builder.cpp.i

src/daemon/json_builder.s: src/daemon/json_builder.cpp.s

.PHONY : src/daemon/json_builder.s

# target to generate assembly for a file
src/daemon/json_builder.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/json_builder.cpp.s
.PHONY : src/daemon/json_builder.cpp.s

src/daemon/judge.o: src/daemon/judge.cpp.o

.PHONY : src/daemon/judge.o

# target to build an object file
src/daemon/judge.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/judge.cpp.o
.PHONY : src/daemon/judge.cpp.o

src/daemon/judge.i: src/daemon/judge.cpp.i

.PHONY : src/daemon/judge.i

# target to preprocess a source file
src/daemon/judge.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/judge.cpp.i
.PHONY : src/daemon/judge.cpp.i

src/daemon/judge.s: src/daemon/judge.cpp.s

.PHONY : src/daemon/judge.s

# target to generate assembly for a file
src/daemon/judge.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/judge.cpp.s
.PHONY : src/daemon/judge.cpp.s

src/daemon/manager.o: src/daemon/manager.cpp.o

.PHONY : src/daemon/manager.o

# target to build an object file
src/daemon/manager.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/manager.cpp.o
.PHONY : src/daemon/manager.cpp.o

src/daemon/manager.i: src/daemon/manager.cpp.i

.PHONY : src/daemon/manager.i

# target to preprocess a source file
src/daemon/manager.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/manager.cpp.i
.PHONY : src/daemon/manager.cpp.i

src/daemon/manager.s: src/daemon/manager.cpp.s

.PHONY : src/daemon/manager.s

# target to generate assembly for a file
src/daemon/manager.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/manager.cpp.s
.PHONY : src/daemon/manager.cpp.s

src/daemon/readconfig.o: src/daemon/readconfig.cpp.o

.PHONY : src/daemon/readconfig.o

# target to build an object file
src/daemon/readconfig.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/readconfig.cpp.o
.PHONY : src/daemon/readconfig.cpp.o

src/daemon/readconfig.i: src/daemon/readconfig.cpp.i

.PHONY : src/daemon/readconfig.i

# target to preprocess a source file
src/daemon/readconfig.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/readconfig.cpp.i
.PHONY : src/daemon/readconfig.cpp.i

src/daemon/readconfig.s: src/daemon/readconfig.cpp.s

.PHONY : src/daemon/readconfig.s

# target to generate assembly for a file
src/daemon/readconfig.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/readconfig.cpp.s
.PHONY : src/daemon/readconfig.cpp.s

src/daemon/validator.o: src/daemon/validator.cpp.o

.PHONY : src/daemon/validator.o

# target to build an object file
src/daemon/validator.cpp.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/validator.cpp.o
.PHONY : src/daemon/validator.cpp.o

src/daemon/validator.i: src/daemon/validator.cpp.i

.PHONY : src/daemon/validator.i

# target to preprocess a source file
src/daemon/validator.cpp.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/validator.cpp.i
.PHONY : src/daemon/validator.cpp.i

src/daemon/validator.s: src/daemon/validator.cpp.s

.PHONY : src/daemon/validator.s

# target to generate assembly for a file
src/daemon/validator.cpp.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_daemon.dir/build.make CMakeFiles/cwoj_daemon_daemon.dir/src/daemon/validator.cpp.s
.PHONY : src/daemon/validator.cpp.s

src/runner/runner_linux.o: src/runner/runner_linux.c.o

.PHONY : src/runner/runner_linux.o

# target to build an object file
src/runner/runner_linux.c.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/runner_linux.c.o
.PHONY : src/runner/runner_linux.c.o

src/runner/runner_linux.i: src/runner/runner_linux.c.i

.PHONY : src/runner/runner_linux.i

# target to preprocess a source file
src/runner/runner_linux.c.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/runner_linux.c.i
.PHONY : src/runner/runner_linux.c.i

src/runner/runner_linux.s: src/runner/runner_linux.c.s

.PHONY : src/runner/runner_linux.s

# target to generate assembly for a file
src/runner/runner_linux.c.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/runner_linux.c.s
.PHONY : src/runner/runner_linux.c.s

src/runner/sablebox.o: src/runner/sablebox.c.o

.PHONY : src/runner/sablebox.o

# target to build an object file
src/runner/sablebox.c.o:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/sablebox.c.o
.PHONY : src/runner/sablebox.c.o

src/runner/sablebox.i: src/runner/sablebox.c.i

.PHONY : src/runner/sablebox.i

# target to preprocess a source file
src/runner/sablebox.c.i:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/sablebox.c.i
.PHONY : src/runner/sablebox.c.i

src/runner/sablebox.s: src/runner/sablebox.c.s

.PHONY : src/runner/sablebox.s

# target to generate assembly for a file
src/runner/sablebox.c.s:
	$(MAKE) -f CMakeFiles/cwoj_daemon_runner.dir/build.make CMakeFiles/cwoj_daemon_runner.dir/src/runner/sablebox.c.s
.PHONY : src/runner/sablebox.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cwoj_daemon_runner"
	@echo "... edit_cache"
	@echo "... cwoj_daemon_daemon"
	@echo "... src/daemon/call_ruc.o"
	@echo "... src/daemon/call_ruc.i"
	@echo "... src/daemon/call_ruc.s"
	@echo "... src/daemon/cena_validator.o"
	@echo "... src/daemon/cena_validator.i"
	@echo "... src/daemon/cena_validator.s"
	@echo "... src/daemon/database.o"
	@echo "... src/daemon/database.i"
	@echo "... src/daemon/database.s"
	@echo "... src/daemon/http.o"
	@echo "... src/daemon/http.i"
	@echo "... src/daemon/http.s"
	@echo "... src/daemon/json_builder.o"
	@echo "... src/daemon/json_builder.i"
	@echo "... src/daemon/json_builder.s"
	@echo "... src/daemon/judge.o"
	@echo "... src/daemon/judge.i"
	@echo "... src/daemon/judge.s"
	@echo "... src/daemon/manager.o"
	@echo "... src/daemon/manager.i"
	@echo "... src/daemon/manager.s"
	@echo "... src/daemon/readconfig.o"
	@echo "... src/daemon/readconfig.i"
	@echo "... src/daemon/readconfig.s"
	@echo "... src/daemon/validator.o"
	@echo "... src/daemon/validator.i"
	@echo "... src/daemon/validator.s"
	@echo "... src/runner/runner_linux.o"
	@echo "... src/runner/runner_linux.i"
	@echo "... src/runner/runner_linux.s"
	@echo "... src/runner/sablebox.o"
	@echo "... src/runner/sablebox.i"
	@echo "... src/runner/sablebox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

